/**
 * Represents a single act in the generated poem structure.
 */
export interface PoemAct {
    /** The starting phrase provided by the system/persona. */
    starter: string;
    /** A list of possible completions generated by the AI. */
    suggestions: string[];
}

/**
 * The raw result from the Image Analysis phase.
 */
export interface AnalysisResult {
    acts: PoemAct[];
    /** Visual descriptors extracted from the image. */
    visual_tags: string[];
    /** Optional caption for visual-only modes. */
    caption?: string;
}

/**
 * Represents a completed, generated postcard artifact.
 * Stored in the cache to allow instant retrieval when switching themes.
 */
export interface Artifact {
    themeId: string;
    /** Base64 data of the stylized image. */
    imageUrl: string;
    /** The final, user-selected poem text. */
    poem: string;
    /** The full prompt used to generate the image. */
    prompt: string;
    /** Version of the prompt logic used. */
    version: string;
    /** Timestamp of generation. */
    timestamp: number;
}
